name: hello-world

on:
  workflow_dispatch:
    inputs:
      MY_VAR:
        description: 'Enter your variable value'
        required: true
        default: "hello"

env:
  MY_VAR: ${{ inputs.MY_VAR }}

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "Hi Padma"

      - name: Print MY_VAR
        run: echo "MY_VAR is $MY_VAR"
